language: node_js
node_js:
  - 'stable'
services:
  - xvfb
addons:
  firefox: latest
  chrome: stable
before_install:
  - corepack enable pnpm
install:
  - pnpm install --frozen-lockfile
  - pnpm build
script:
  - pnpm test:svgdom
  - pnpm test
  - pnpm exec coveralls < coverage/firefox/lcov.info
